import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import { useState } from "react";

const portfolio = () => {
  const [isActive, setIsActive] = useState(false);
  const toggleClass = () => {
    setIsActive(!isActive);
  };
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/public/css/photoswipe-skin.css" />
        <link rel="stylesheet" href="/public/css/photoswipe.css" />
        <link rel="stylesheet" href="/public/css/BeerSlider.css" />
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></Script>
        <Script src="https://code.jquery.com/jquery-3.4.1.min.js"></Script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.js"></Script>
        <Script src="https://andyhardy.co/assets/js/navigation.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/cookies.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/observers.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/parallax.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/photoswipe.min.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/photoswipe-ui-default.min.js"></Script>{" "}
        <Script src="https://andyhardy.co/assets/js/photoswipe.js"></Script>
      </Head>

      <main className={isActive ? "active" : ""} id="portfolio">
        <div className="black-overlay"></div>
        <div className="navigation-fade"></div>
        <a href="https://andyhardy.co" className="logo animatelink">
          <img
            src="https://andyhardy.co/assets/img/logo-andy.png"
            height="23"
          />
        </a>
        <nav className={isActive ? "active" : ""}>
          <div
            className="background-image"
            style={{
              background:
                "url('https://andyhardy.co/media/site/6ea6b50483-1631837366/andrew-footer-1600x1080.jpg') center center",
              backgroundSize: "cover",
            }}
          ></div>
          <div className="top-fade"></div>
          <div className="left-fade"></div>
          <ul>
            <li className="big-li">
              <Link href="/" className="animatelink">
                Homepage
              </Link>
            </li>
            <li className="big-li ">
              <Link href="/portfolio" className="animatelink">
                Portfolio
              </Link>
            </li>
            <li className="big-li ">
              <Link href="/" className="animatelink">
                Motion
              </Link>
            </li>
            <div className="external-links">
              <a href="https://emble.studio/" target="_blank">
                <h3>Commercial Work</h3>
                <svg width="12" height="12">
                  <g stroke="#FFF" fill="none" fillRule="evenodd">
                    <path d="M3 1h8v8M11 1L1 11" />
                  </g>
                </svg>
              </a>
              <a href="https://momentsinaminute.com/" target="_blank">
                <h3>Education</h3>
                <svg width="12" height="12">
                  <g stroke="#FFF" fill="none" fillRule="evenodd">
                    <path d="M3 1h8v8M11 1L1 11" />
                  </g>
                </svg>
              </a>
              <a href="/film-luts">
                <h3>My presets</h3>
                <svg width="12" height="12">
                  <g stroke="#FFF" fill="none" fillRule="evenodd">
                    <path d="M3 1h8v8M11 1L1 11" />
                  </g>
                </svg>
              </a>
              <a
                href="https://andrewhardy.pixieset.com/felanprints/"
                target="_blank"
              >
                <h3>Prints</h3>
                <svg width="12" height="12">
                  <g stroke="#FFF" fill="none" fillRule="evenodd">
                    <path d="M3 1h8v8M11 1L1 11" />
                  </g>
                </svg>
              </a>
            </div>
          </ul>
        </nav>
        <a href="mailto:hello@andyhardy.co" className="btn nav-cta-btn">
          <span>Get in touch</span>
        </a>
        <div
          className={isActive ? "nav-icon active" : "nav-icon"}
          onClick={toggleClass}
        >
          <div className="hamburger-bar"></div>
        </div>
        {/* Social Icon */}
        <div className="social-ico-block">
          <a
            href="https://www.instagram.com/"
            target="_blank"
            className="social-ico"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M12,3.8c2.67,0,2.986.01,4.041.058A5.552,5.552,0,0,1,17.9,4.2a3.31,3.31,0,0,1,1.9,1.9,5.552,5.552,0,0,1,.344,1.857C20.188,9.014,20.2,9.33,20.2,12s-.01,2.986-.058,4.041A5.552,5.552,0,0,1,19.8,17.9a3.31,3.31,0,0,1-1.9,1.9,5.552,5.552,0,0,1-1.857.344c-1.054.048-1.371.058-4.041.058s-2.987-.01-4.041-.058A5.552,5.552,0,0,1,6.1,19.8a3.31,3.31,0,0,1-1.9-1.9,5.552,5.552,0,0,1-.344-1.857C3.812,14.986,3.8,14.67,3.8,12s.01-2.986.058-4.041A5.552,5.552,0,0,1,4.2,6.1,3.31,3.31,0,0,1,6.1,4.2,5.552,5.552,0,0,1,7.959,3.86C9.014,3.812,9.33,3.8,12,3.8M12,2c-2.716,0-3.056.012-4.123.06a7.355,7.355,0,0,0-2.427.465A5.106,5.106,0,0,0,2.525,5.45,7.355,7.355,0,0,0,2.06,7.877C2.012,8.944,2,9.284,2,12s.012,3.056.06,4.123a7.355,7.355,0,0,0,.465,2.427A5.106,5.106,0,0,0,5.45,21.475a7.355,7.355,0,0,0,2.427.465C8.944,21.989,9.284,22,12,22s3.056-.011,4.123-.06a7.355,7.355,0,0,0,2.427-.465,5.106,5.106,0,0,0,2.925-2.925,7.355,7.355,0,0,0,.465-2.427c.048-1.067.06-1.407.06-4.123s-.012-3.056-.06-4.123a7.355,7.355,0,0,0-.465-2.427A5.106,5.106,0,0,0,18.55,2.525a7.355,7.355,0,0,0-2.427-.465C15.056,2.012,14.716,2,12,2Z" />
              <path d="M12,6.865A5.135,5.135,0,1,0,17.135,12,5.135,5.135,0,0,0,12,6.865Zm0,8.468A3.333,3.333,0,1,1,15.333,12,3.333,3.333,0,0,1,12,15.333Z" />
              <circle cx="17.338" cy="6.662" r="1.2" />
            </svg>
          </a>
          <a
            href="https://vimeo.com/andrewhardy"
            target="_blank"
            className="social-ico"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M20.983,7.812q-.119,2.629-3.671,7.207Q13.636,19.8,11.1,19.8c-1.057,0-1.934-.971-2.665-2.911L6.992,11.55q-.81-2.907-1.734-2.909a5.559,5.559,0,0,0-1.411.849L3,8.4Q4.334,7.224,5.626,6.052A5.952,5.952,0,0,1,8.291,4.433q2.1-.2,2.586,2.878.522,3.323.728,4.13.606,2.757,1.332,2.756.564,0,1.7-1.789a7.043,7.043,0,0,0,1.208-2.721c.108-1.028-.3-1.546-1.21-1.546a3.277,3.277,0,0,0-1.333.293c.89-2.9,2.576-4.317,5.072-4.227,1.854.045,2.721,1.248,2.619,3.6Z" />
            </svg>
          </a>
          <a
            href="https://www.facebook.com/"
            target="_blank"
            className="social-ico"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M22.06,11.987a10.061,10.061,0,1,0-11.633,9.939V14.9H7.872V11.987h2.555V9.771a3.551,3.551,0,0,1,3.8-3.915,15.427,15.427,0,0,1,2.252.2V8.529H15.211a1.454,1.454,0,0,0-1.64,1.571v1.887h2.791L15.915,14.9H13.571v7.03A10.064,10.064,0,0,0,22.06,11.987Z" />
            </svg>
          </a>
          <a
            href="https://www.youtube.com/"
            target="_blank"
            className="social-ico"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="M22.062,6.927A2.631,2.631,0,0,0,20.234,5.1c-1.637-.439-8.224-.439-8.224-.439S5.439,4.652,3.785,5.1A2.631,2.631,0,0,0,1.957,6.927,27.322,27.322,0,0,0,1.5,12.009a27.287,27.287,0,0,0,.456,5.062A2.631,2.631,0,0,0,3.785,18.9c1.635.44,8.225.44,8.225.44s6.57,0,8.224-.44a2.631,2.631,0,0,0,1.828-1.827,27.364,27.364,0,0,0,.438-5.062A27.406,27.406,0,0,0,22.062,6.927ZM9.907,15.152v-6.3l5.483,3.153Z" />
            </svg>
          </a>
        </div>
        {/* Logo */}
        <div className="home-overlay fade-in appear">
          <img
            src="https://andyhardy.co/assets/img/logo-andy.png"
            height="23"
          />
        </div>
        <Link href="/" className="logo-home animatelink">
          <h3 className="logo-name">Andrew Hardy</h3>
          <img
            src="https://andyhardy.co/assets/img/logo-andy.png"
            height="23"
          />
        </Link>
        {/* Filter */}
        <section className="filter">
          <div className="wrap">
            <ul className="tags">
              <li>
                <Link className="animatelink active" href="/portfolio">
                  all
                </Link>
              </li>
              <li>
                <Link
                  className="animatelink"
                  href="/portfolio/tag:accommodation"
                >
                  accommodation{" "}
                </Link>
              </li>
              <li>
                <Link className="animatelink" href="/portfolio/tag:adventure">
                  adventure{" "}
                </Link>
              </li>
              <li>
                <Link className="animatelink" href="/portfolio/tag:people">
                  people{" "}
                </Link>
              </li>
            </ul>
          </div>
        </section>
        {/* Grid */}

        <section className="grid">
          <div className="wrap-wide appear">
            <div
              class="photoswipe-wrapper fade-in appear"
              itemScope
              itemType="http://schema.org/ImageGallery"
            >
              <div class="photoswipe-item fade-in appear appear">
                <a
                  href="https://andyhardy.co/media/pages/portfolio/78f2f24c07-1631837366/andy-hardy-people-portraits-photographer-australia-1-2160x2160.jpg"
                  itemprop="contentUrl"
                  data-size="1440x1800"
                >
                  <img
                    src="https://andyhardy.co/media/pages/portfolio/78f2f24c07-1631837366/andy-hardy-people-portraits-photographer-australia-1-400x400-q72.jpg"
                    width="1440"
                    height="1800"
                  />
                  {/* <div class="overlay"></div> */}
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path
                      d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z"
                      fill="none"
                      stroke="#fff"
                      stroke-width="1.5"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="3"
                      fill="none"
                      stroke="#fff"
                      stroke-width="1.5"
                    />
                  </svg>
                </a>
              </div>
              <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/e628c14d87-1631837366/andy-hardy-people-portraits-photographer-australia-2-2160x2160.jpg" itemprop="contentUrl" data-size="1500x1000" >
                  <img src="https://andyhardy.co/media/pages/portfolio/e628c14d87-1631837366/andy-hardy-people-portraits-photographer-australia-2-400x400-q72.jpg" width="1500" height="1000"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/d5b480ca70-1631837366/andy-hardy-people-portraits-photographer-australia-3-2160x2160.jpg" itemprop="contentUrl" data-size="1333x2000" >
                  <img src="https://andyhardy.co/media/pages/portfolio/d5b480ca70-1631837366/andy-hardy-people-portraits-photographer-australia-3-400x400-q72.jpg" width="1333" height="2000"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/e15f2df4df-1631837366/andy-hardy-people-portraits-photographer-australia-10-2160x2160.jpg" itemprop="contentUrl" data-size="1336x2000" >
                  <img src="https://andyhardy.co/media/pages/portfolio/e15f2df4df-1631837366/andy-hardy-people-portraits-photographer-australia-10-400x400-q72.jpg" width="1336" height="2000"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/0ee65cc047-1631837366/andy-hardy-people-portraits-photographer-australia-5-2160x2160.jpg" itemprop="contentUrl" data-size="2000x1333" >
                  <img src="https://andyhardy.co/media/pages/portfolio/0ee65cc047-1631837366/andy-hardy-people-portraits-photographer-australia-5-400x400-q72.jpg" width="2000" height="1333"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/51ede97af6-1631837366/andy-hardy-people-portraits-photographer-australia-7-2160x2160.jpg" itemprop="contentUrl" data-size="1240x1748" >
                  <img src="https://andyhardy.co/media/pages/portfolio/51ede97af6-1631837366/andy-hardy-people-portraits-photographer-australia-7-400x400-q72.jpg" width="1240" height="1748"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            <div class="photoswipe-item fade-in appear">
               <a href="https://andyhardy.co/media/pages/portfolio/8430a83143-1631837366/andy-hardy-people-portraits-photographer-australia-4-2160x2160.jpg" itemprop="contentUrl" data-size="1600x2000" >
                  <img src="https://andyhardy.co/media/pages/portfolio/8430a83143-1631837366/andy-hardy-people-portraits-photographer-australia-4-400x400-q72.jpg" width="1600" height="2000"/>
                  <div class="overlay"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,12a11.6,11.6,0,0,1-10,6A11.6,11.6,0,0,1,2,12,11.6,11.6,0,0,1,12,6,11.6,11.6,0,0,1,22,12Z" fill="none" stroke="#fff" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="none" stroke="#fff" stroke-width="1.5"/></svg>
               </a>
            </div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer>
          <div
            className="background-image"
            style={{
              background:
                "url('https://andyhardy.co/media/site/6ea6b50483-1631837366/andrew-footer-1600x1080.jpg') center center no-repeat",
              backgroundSize: "cover",
            }}
          ></div>
          <div className="top-fade"></div>
          <div className="left-fade"></div>
          <div className="wrap-text">
            <a href="mailto:hello@andyhardy.co" className="mail">
              hello@andyhardy.co
            </a>
            <div className="logo-row">
              <img
                src="https://andyhardy.co/assets/img/logo-andy.png"
                height="23"
              />
            </div>
            <div className="credits-row">
              <li>© 2023 Andrew Hardy</li>
              <li>/</li>
              <li>
                <a href="https://www.dennissnellenberg.nl/en" target="_blank">
                  Code by Dennis
                </a>
              </li>
            </div>
          </div>
          <div className="social-ico-block">
            <a
              href="https://www.instagram.com/andrewhardy/"
              target="_blank"
              className="social-ico"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M12,3.8c2.67,0,2.986.01,4.041.058A5.552,5.552,0,0,1,17.9,4.2a3.31,3.31,0,0,1,1.9,1.9,5.552,5.552,0,0,1,.344,1.857C20.188,9.014,20.2,9.33,20.2,12s-.01,2.986-.058,4.041A5.552,5.552,0,0,1,19.8,17.9a3.31,3.31,0,0,1-1.9,1.9,5.552,5.552,0,0,1-1.857.344c-1.054.048-1.371.058-4.041.058s-2.987-.01-4.041-.058A5.552,5.552,0,0,1,6.1,19.8a3.31,3.31,0,0,1-1.9-1.9,5.552,5.552,0,0,1-.344-1.857C3.812,14.986,3.8,14.67,3.8,12s.01-2.986.058-4.041A5.552,5.552,0,0,1,4.2,6.1,3.31,3.31,0,0,1,6.1,4.2,5.552,5.552,0,0,1,7.959,3.86C9.014,3.812,9.33,3.8,12,3.8M12,2c-2.716,0-3.056.012-4.123.06a7.355,7.355,0,0,0-2.427.465A5.106,5.106,0,0,0,2.525,5.45,7.355,7.355,0,0,0,2.06,7.877C2.012,8.944,2,9.284,2,12s.012,3.056.06,4.123a7.355,7.355,0,0,0,.465,2.427A5.106,5.106,0,0,0,5.45,21.475a7.355,7.355,0,0,0,2.427.465C8.944,21.989,9.284,22,12,22s3.056-.011,4.123-.06a7.355,7.355,0,0,0,2.427-.465,5.106,5.106,0,0,0,2.925-2.925,7.355,7.355,0,0,0,.465-2.427c.048-1.067.06-1.407.06-4.123s-.012-3.056-.06-4.123a7.355,7.355,0,0,0-.465-2.427A5.106,5.106,0,0,0,18.55,2.525a7.355,7.355,0,0,0-2.427-.465C15.056,2.012,14.716,2,12,2Z" />
                <path d="M12,6.865A5.135,5.135,0,1,0,17.135,12,5.135,5.135,0,0,0,12,6.865Zm0,8.468A3.333,3.333,0,1,1,15.333,12,3.333,3.333,0,0,1,12,15.333Z" />
                <circle cx="17.338" cy="6.662" r="1.2" />
              </svg>
            </a>
            <a
              href="https://vimeo.com/andrewhardy"
              target="_blank"
              className="social-ico"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M20.983,7.812q-.119,2.629-3.671,7.207Q13.636,19.8,11.1,19.8c-1.057,0-1.934-.971-2.665-2.911L6.992,11.55q-.81-2.907-1.734-2.909a5.559,5.559,0,0,0-1.411.849L3,8.4Q4.334,7.224,5.626,6.052A5.952,5.952,0,0,1,8.291,4.433q2.1-.2,2.586,2.878.522,3.323.728,4.13.606,2.757,1.332,2.756.564,0,1.7-1.789a7.043,7.043,0,0,0,1.208-2.721c.108-1.028-.3-1.546-1.21-1.546a3.277,3.277,0,0,0-1.333.293c.89-2.9,2.576-4.317,5.072-4.227,1.854.045,2.721,1.248,2.619,3.6Z" />
              </svg>
            </a>
            <a
              href="https://www.facebook.com/groups/MomentsinaMinute"
              target="_blank"
              className="social-ico"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M22.06,11.987a10.061,10.061,0,1,0-11.633,9.939V14.9H7.872V11.987h2.555V9.771a3.551,3.551,0,0,1,3.8-3.915,15.427,15.427,0,0,1,2.252.2V8.529H15.211a1.454,1.454,0,0,0-1.64,1.571v1.887h2.791L15.915,14.9H13.571v7.03A10.064,10.064,0,0,0,22.06,11.987Z" />
              </svg>
            </a>
            <a
              href="https://www.youtube.com/channel/UCPtO-spPgWBirAs_Qa6OIew/"
              target="_blank"
              className="social-ico"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M22.062,6.927A2.631,2.631,0,0,0,20.234,5.1c-1.637-.439-8.224-.439-8.224-.439S5.439,4.652,3.785,5.1A2.631,2.631,0,0,0,1.957,6.927,27.322,27.322,0,0,0,1.5,12.009a27.287,27.287,0,0,0,.456,5.062A2.631,2.631,0,0,0,3.785,18.9c1.635.44,8.225.44,8.225.44s6.57,0,8.224-.44a2.631,2.631,0,0,0,1.828-1.827,27.364,27.364,0,0,0,.438-5.062A27.406,27.406,0,0,0,22.062,6.927ZM9.907,15.152v-6.3l5.483,3.153Z" />
              </svg>
            </a>
          </div>{" "}
        </footer>
      </main>
    </>
  );
};

export default portfolio;
